### ISSUE TITLE
Instell Shell Script does not work

### ISSUE THREAD

**Issue by jKelio** [data-mill-cloud/data-mill#8]
I got the following error after executing the install shell script:

![image](https://user-images.githubusercontent.com/20369002/56745089-05a6cf80-677a-11e9-840b-91794d739e3d.png)

**Comment by pilillo** [comment]
Tested on main Linux distros, untested on Mac. I anyways fixed the install.sh to work for mac, rest of run.sh is still untested for Mac. Feel free to file further tickets if you encounter issues.
